### ISSUE TITLE
Implement Masters age grade tables and code

### ISSUE THREAD

**Issue by captainrobbo** [openath/athlib#2]
The canonical homes for these are here [(track and field)](http://www.howardgrubb.co.uk/athletics/wmatnf14.html) and [here (road)](http://www.howardgrubb.co.uk/athletics/wmaroad15.html).  ReportLab has previously done an [age grade calculator](http://www.reportlab.com/sp/agegrade.html) which might be useful

**Comment by PelagicGames** [comment]
This appears to have been done for Python, so I'm porting to JavaScript now, using the same directory structure beneath `js`.
